version: '2'
services:
  gps-client:
    build: ./client
    ports:
      - "8080:8080"
    links:
      - gps-server
    depends_on:
      - gps-server
  gps-server:
    build: ./server
    links:
      - gps-db
    ports:
      - "3001:3001"
    depends_on:
      - gps-db
  gps-db:
    image: mongo:3.2
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/db/:/data/db
      - ./volumes/configdb/:/data/configdb
