export const UPLOAD_FILE_REQUEST = '@upload/UPLOAD_FILE_REQUEST';
export const UPLOAD_FILE_RESPONSE = '@upload/UPLOAD_FILE_RESPONSE';

export const UPLOAD_TRACK_REQUEST = '@upload/UPLOAD_TRACK_REQUEST';
export const UPLOAD_TRACK_RESPONSE = '@upload/UPLOAD_TRACK_RESPONSE';
